version: "2"

run:
  concurrency: 8
  timeout: 5m
  skip-dirs:
    - vendor
    - .git
    - "api/docs"
    - internal/mocks
    - testdata
    - bin
  skip-files:
    - "*_test.go"
    - "*.pb.go"
    - "*.gw.go"
    - "*.easyjson.go"

linters:
  enable:
    # Основные линтеры
    - govet       # Стандартные проверки Go
    - staticcheck # Продвинутый статический анализ (включает unused)
    - revive      # Проверка стиля
    - gocritic    # Критический анализ кода

    # Безопасность
    - gosec

    # Дополнительные проверки
    - errcheck    # Проверка обработки ошибок
    - nilerr      # Проверка избыточных nil-проверок
    - dupl        # Поиск дубликатов кода
    - goconst     # Поиск магических строк/чисел
    - prealloc    # Проверка предварительной аллокации
    - bodyclose   # Проверка закрытия HTTP body
    - lll         # Проверка длины строк

  settings:
    revive:
      rules:
        - name: package-comments
          severity: warning
        - name: exported
          severity: error
          arguments: [ "disableStutteringCheck" ]
        - name: unused-parameter
          severity: warning  # Добавлено правило для неиспользованных параметров

    gocritic:
      enabled-checks:
        - hugeParam
        - rangeExprCopy
        - sloppyReassign
      settings:
        rangeExprCopy:
          sizeThreshold: 128

    gosec:
      excludes:
        - G104 # errcheck делает это лучше
        - G307 # defer close проверка

    dupl:
      threshold: 30

    lll:
      line-length: 120
      tab-width: 1
      ignore-generated: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test.go"
      linters:
        - dupl
        - gocritic
    - path: "*.pb.go"
      linters:
        - revive
    - text: "Error return value of .* not checked"
      linters:
        - errcheck
    - text: "unused parameter"  # Исключение для неиспользованных параметров
      linters:
        - revive

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true